// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreateanewpostTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void createanewpost() {
        driver.get("http://127.0.0.1:7000/");
        driver.manage().window().setSize(new Dimension(1118, 835));
        driver.findElement(By.linkText("Sign in")).click();
        driver.findElement(By.id("sign-in__email")).click();
        driver.findElement(By.id("sign-in__email")).sendKeys("alinatimchenko24@gmail.com");
        driver.findElement(By.id("sign-in__password")).click();
        driver.findElement(By.id("sign-in__password")).sendKeys("scadm125-Timli");
        driver.findElement(By.cssSelector(".form__button")).click();
        driver.findElement(By.linkText("New post")).click();
        driver.findElement(By.cssSelector(".post-form__title")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".post-form__title"));
            js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'Тест 5'}", element);
        }
        driver.findElement(By.cssSelector(".post-form__description")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".post-form__description"));
            js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'Тут буде текст для тесту 5.'}", element);
        }
        driver.findElement(By.cssSelector(".post-form__button:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".alert__button")).click();
    }
}